FORMAT: 1A

# WebServices mock API
User API is a service to manage users.

# Group User
User related resources of the **User API**

## User Login [/users/login]
### Login [POST]
+ Request (application/json)

        { "username": "moto.origamitech", "pwd": "MD5_pwD"}

+ Response 200 (application/json)

        {
            "result" : {
                "success" : true,   
                "message" : ""
            },
            "data" : { 
                "id" : 1234,
                "firstName": "Alma",
                "lastName": "Patterson",
                "photo": "portraits/med/women/48.jpg",
                "gender" : 2,
                "email" : "alma.patterson37@example.com",
                "phone" : "+55 11 98272-1828",
                "mainUser" : true,
                "about" : "Hi! I'm a mototech",
                "birthDate" : "10/10/2010",
                "username": "alma",
                "accessToken": "XPTOACCESS",
                "address": "Rua Fernao Dias 88",
                "city": "São Paulo",
                "zipcode": "11221-000",
                "rating": "3.5",
                "estimatedTime": "7",
                "workHour": "8:00 am - 5:00 pm",
                "status": true
            }
        }

+ Response 400 (application/json)
        
        {
            "result" : {
                "success" : false,   
                "message" : ""
            },
            "data" : {
            }
        }

## User Dashboard [/users/{id}/dashboard]
### Dashboard [GET]
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the User to perform action with. Has example value.

+ Response 200 (application/json)

        {
            "result" : {
                "success" : true,   
                "message" : ""
            },
            "data" : {
                "dashboardItems": [{
                    "id" : 1,
                    "description" : "Accepted Requests",
                    "count" : 5
                },
                {
                    "id" : 2,
                    "description" : "Requests",
                    "count" : 3
                },
                {
                    "id" : 3,
                    "description" : "Opened Services",
                    "count" : 5
                }]
            }
        }

+ Response 400 (application/json)
        
        {
            "result" : {
                "success" : false,   
                "message" : "Error into dashboard request"
            },
            "data" : {
            }
        }

## User received requests [/users/{id}/appointments]
### Received Requests [GET]
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the User to perform action with. Has example value.

+ Response 200 (application/json)

        {
            "result" : {
                "success" : true,
                "message" : ""
            },
            "data" : [
                {
                    "user" : {
                        "id" : 123,
                        "type" : 2,
                        "typeDescription" : "client",
                        "firstName": "Rafael",
                        "lastName": "Garg",
                        "photo": "sPsqQoM.jpg",
                        "gender" : 1,
                        "email" : "mototech@origamitech.com.br",
                        "phone" : "+55 11 98272-1828",
                        "mainUser" : false,
                        "about" : "Hi! I'm a moto client",
                        "username": "moto.origamitech"
                    },
                    "status" : "accepted",
                    "statusId" : 1,
                    "issue": "Problemas na Bateria",
                    "date" : "14/03/2015 15:00",
                    "suggestedAddress" : "5118 depaul dr",
                    "number" : "300",
                    "suggestedDate" : "15/03/2015 12:00",
                    "id" : 1,
                    "latitude" : -23.556472,
                    "longitude" : -46.703755,
                    "complement" : "Minha bateria parou de carregar"
                },
                {
                    "user" : {
                        "id" : 321,
                        "type" : 2,
                        "typeDescription" : "client",
                        "firstName": "John",
                        "lastName": "Cocci",
                        "photo": "JoPjhi8.jpg",
                        "gender" : 1,
                        "email" : "mototech@origamitech.com.br",
                        "phone" : "+55 11 98272-1828",
                        "mainUser" : false,
                        "about" : "Hi! I'm a moto client",
                        "username": "moto.origamitech"
                    },
                    "status" : "pending",
                    "statusId" : 2,
                    "issue": "Problemas na tela",
                    "date" : "14/03/2015 15:00",
                    "suggestedAddress" : "Rua Wizard",
                    "number" : "300",
                    "suggestedDate" : "15/03/2015 12:00",
                    "id" : 2,
                    "latitude" : -23.555568,
                    "longitude" : -46.703529,
                    "complement" : "Minha tela esta com faixas azuis"
                },
                {
                    "user" : {
                        "id" : 456,
                        "type" : 2,
                        "typeDescription" : "client",
                        "firstName": "Christian",
                        "lastName": "Ambre",
                        "photo": "sPsqQoM.jpg",
                        "gender" : 1,
                        "email" : "mototech@origamitech.com.br",
                        "phone" : "+55 11 98272-1828",
                        "mainUser" : false,
                        "about" : "Hi! I'm a moto client",
                        "username": "moto.origamitech"
                    },
                    "status" : "accepted",
                    "statusId" : 1,
                    "issue": "Problemas na Baaaateria",
                    "date" : "14/03/2015 15:00",
                    "suggestedAddress" : "t aliquam seasdm lorem et",
                    "number" : "300",
                    "suggestedDate" : "15/03/2015 13:00",
                    "id" : 3,
                    "latitude" : -23.556462,
                    "longitude" : -46.706748,
                    "complement" : "ALorem iasdadpsum dolor sit amet"
                },
                {
                    "user" : {
                        "id" : 654,
                        "type" : 2,
                        "typeDescription" : "client",
                        "firstName": "Ronald",
                        "lastName": "River",
                        "photo": "JoPjhi8.jpg",
                        "gender" : 1,
                        "email" : "mototech@origamitech.com.br",
                        "phone" : "+55 11 98272-1828",
                        "mainUser" : false,
                        "about" : "Hi! I'm a moto client",
                        "username": "moto.origamitech"
                    },
                    "status" : "pending",
                    "statusId" : 2,
                    "issue": "Problemas na tela",
                    "date" : "14/03/2015 15:00",
                    "suggestedAddress" : "Rua Wizard",
                    "number" : "300",
                    "suggestedDate" : "15/03/2015 12:00",
                    "id" : 4,
                    "latitude" : -23.554593,
                    "longitude" : -46.703401,
                    "complement" : "t aliquam sem lorem et"
                }
            ]
        }

+ Response 400 (application/json)
        
        {
            "result" : {
                "success" : false,   
                "message" : "Error into request"
            },
            "data" : {
            }
        }

## User Opened Services [/users/{id}/openedServices]
### Opened Services [GET]
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the User to perform action with. Has example value.

+ Response 200 (application/json)

        {
            "result" : {
                "success" : true,
                "message" : ""
            },
            "data" : 
                [{
                    "number" : "WO00441331",
                    "swWarrantyStart" : "12/12/2015",
                    "swWarrantyEnd" : "12/12/2018",
                    "hwWarrantyStart" : "12/12/2015",
                    "hwWarrantyEnd" : "12/12/2018",        
                    "typeDescription" : "client",
                    "repairWarrantyStart": "01/05/2015",
                    "repairWarrantyEnd": "01/05/2015",
                    "entitlement": "XPTO",
                    "dueDate": "15/08/2015",
                    "user" : {
                        "id" : 1245,
                        "type" : 2,
                        "typeDescription" : "client",
                        "firstName": "Client",
                        "lastName": "4",
                        "photo": "JoPjhi8.jpg",
                        "gender" : 1,
                        "email" : "mototech@origamitech.com.br",
                        "phone" : "+55 11 98272-1828",
                        "mainUser" : false,
                        "about" : "Hi! I'm a moto client",
                        "username": "moto.origamitech"
                    }
                },
                {
                    "number" : "WO00441315",
                    "swWarrantyStart" : "12/12/2015",
                    "swWarrantyEnd" : "12/12/2018",
                    "hwWarrantyStart" : "12/12/2015",
                    "hwWarrantyEnd" : "12/12/2018",        
                    "typeDescription" : "client",
                    "repairWarrantyStart": "01/05/2015",
                    "repairWarrantyEnd": "01/05/2015",
                    "entitlement": "XPTO",
                    "dueDate": "15/08/2015",
                    "user" : {
                        "id" : 1245,
                        "type" : 2,
                        "typeDescription" : "client",
                        "firstName": "Client",
                        "lastName": "4",
                        "photo": "JoPjhi8.jpg",
                        "gender" : 1,
                        "email" : "mototech@origamitech.com.br",
                        "phone" : "+55 11 98272-1828",
                        "mainUser" : false,
                        "about" : "Hi! I'm a moto client",
                        "username": "moto.origamitech"
                    }
                },
                {
                    "number" : "WO00442213",
                    "swWarrantyStart" : "12/12/2015",
                    "swWarrantyEnd" : "12/12/2018",
                    "hwWarrantyStart" : "12/12/2015",
                    "hwWarrantyEnd" : "12/12/2018",        
                    "typeDescription" : "client",
                    "repairWarrantyStart": "01/05/2015",
                    "repairWarrantyEnd": "01/05/2015",
                    "entitlement": "XPTO",
                    "dueDate": "15/08/2015",
                    "user" : {
                        "id" : 1245,
                        "type" : 2,
                        "typeDescription" : "client",
                        "firstName": "Client",
                        "lastName": "4",
                        "photo": "JoPjhi8.jpg",
                        "gender" : 1,
                        "email" : "mototech@origamitech.com.br",
                        "phone" : "+55 11 98272-1828",
                        "mainUser" : false,
                        "about" : "Hi! I'm a moto client",
                        "username": "moto.origamitech"
                    }
                },
                {
                    "number" : "WO00424413",
                    "swWarrantyStart" : "12/12/2015",
                    "swWarrantyEnd" : "12/12/2018",
                    "hwWarrantyStart" : "12/12/2015",
                    "hwWarrantyEnd" : "12/12/2018",        
                    "typeDescription" : "client",
                    "repairWarrantyStart": "01/05/2015",
                    "repairWarrantyEnd": "01/05/2015",
                    "entitlement": "XPTO",
                    "dueDate": "15/08/2015",
                    "user" : {
                        "id" : 1245,
                        "type" : 2,
                        "typeDescription" : "client",
                        "firstName": "Client",
                        "lastName": "4",
                        "photo": "JoPjhi8.jpg",
                        "gender" : 1,
                        "email" : "mototech@origamitech.com.br",
                        "phone" : "+55 11 98272-1828",
                        "mainUser" : false,
                        "about" : "Hi! I'm a moto client",
                        "username": "moto.origamitech"
                    }
                },
                {
                    "number" : "WO00445413",
                    "swWarrantyStart" : "12/12/2015",
                    "swWarrantyEnd" : "12/12/2018",
                    "hwWarrantyStart" : "12/12/2015",
                    "hwWarrantyEnd" : "12/12/2018",        
                    "typeDescription" : "client",
                    "repairWarrantyStart": "01/05/2015",
                    "repairWarrantyEnd": "01/05/2015",
                    "entitlement": "XPTO",
                    "dueDate": "15/08/2015",
                    "user" : {
                        "id" : 1245,
                        "type" : 2,
                        "typeDescription" : "client",
                        "firstName": "Client",
                        "lastName": "4",
                        "photo": "JoPjhi8.jpg",
                        "gender" : 1,
                        "email" : "mototech@origamitech.com.br",
                        "phone" : "+55 11 98272-1828",
                        "mainUser" : false,
                        "about" : "Hi! I'm a moto client",
                        "username": "moto.origamitech"
                    }
                }]
        }

+ Response 400 (application/json)
        
        {
            "result" : {
                "success" : false,   
                "message" : "Error into request"
            },
            "data" : {
            }
        }

## User forgot password [/users/forgotPwd]
### Forgot password [POST]
+ Request (application/json)

        { "email": "moto.origamitech@origamitech.com.br"}

+ Response 200 (application/json)

        {
            "result" : {
                "success" : true,   
                "message" : "Solicitacao de reset de senha recebido"
            },
            "data" : {
            }
        }

+ Response 400 (application/json)
        
        {
            "result" : {
                "success" : false,   
                "message" : "Erro no reset de senha"
            },
            "data" : {
            }
        }


## User Collection [/users]
### List all Users [GET]
+ Response 200 (application/json)

        [{
          "id": 1, 
          "name": "Moto origamitech Tech",
          "username": "moto.origamitech"
        }, {
          "id": 2, 
          "name": "Moto origamitech dev",
          "username": "moto.dev"
        }]

## User [/users/{id}]
A single User object with all its details

### Retrieve a User [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body
        
            { "id": 2, "name": "Moto origamitech dev", "username": "moto.dev" }

# Group WebServices mock v1
User related resources of the **WebServices mock API V1**


## User Login V1 [/v1/users/login]
### Login [POST]
+ Request (application/json)

        { 
            "username": "moto.origamitech", 
            "password": "xadsa", 
            "client_id": "f6cd3459f9a39c9784b3e328f05be0f7", 
            "grant_type": "password", 
            "scope": "tech" 
        }

+ Response 200 (application/json)

        {
            "access_token": "XPTOACCESS",
            "scope": "tech",
            "result" : {
                "success" : true,
                "comments":
                /* optional "errorCode" : "",*/
                /* options "errorMessage" : "" */
            },
            "data" : { 
                "id" : 1234,
                "firstName": "Alma",
                "lastName": "Patterson",
                "photo": "DNg1rFD.jpg",
                "gender" : 2,
                "email" : "alma.patterson37@example.com",
                "phone" : "+55 11 98272-1828",
                "mainUser" : true,
                "about" : "Hi! I'm a mototech",
                "birthDate" : "10/10/2010",
                "username": "moto.origamitech",
                "access_token": "XPTOACCESS",
                "address": "Rua Fernao Dias 88",
                "city": "São Paulo",
                "zipcode": "11221-000",
                "rating": "3.5",
                "estimatedTime": "7",
                "workHour": "8:00 am - 5:00 pm",
                "status": true
            }
        }

+ Response 400 (application/json)
        
        {
            "result" : {
                "success" : false,   
                "message" : ""
            },
            "data" : {
            }
        }

## User upload profile picture [/v1/users/{id}/profile_image]
### User profile image [POST]
+ Request (multipart/form-data; boundary=---BOUNDARY)

        -----BOUNDARY
        Content-Disposition: form-data; name="image[file]"; filename="tech_profile.jpg"
        Content-Type: image/jpeg
        Content-Transfer-Encoding: base64

        /9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0a
        HBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIy
        MjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAABAAEDASIA
        AhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFAEB
        AAAAAAAAAAAAAAAAAAAAAP/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AL+AD//Z
        -----BOUNDARY

+ Response 200 (application/json)

        {
            "result" : {
                "success" : true,   
                "message" : ""
            },
            "data" : {
            }
        }

+ Response 400 (application/json)
        
        {
            "result" : {
                "success" : false,   
                "message" : ""
            },
            "data" : {
            }
        }


## User received requests [/v1/users/{id}/appointments]
### Received Requests [GET]
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the User to perform action with. Has example value.

+ Response 200 (application/json)

        {
            "result" : {
                "success" : true,
                "message" : ""
            },
            "data" : [{
                    "appointmentCode" : "1",
                    "user" : {
                        "id" : 121,
                        "type" : 2,
                        "typeDescription" : "client",
                        "firstName": "mark",
                        "lastName": "howard",
                        "photo": "portraits/med/men/55.jpg",
                        "gender" : 1,
                        "email": "mark.howard35@example.com",
                        "phone" : "0741-994-23",
                        "mainUser" : false,
                        "about" : "Hi! I'm a moto client",
                        "username": "whiteswan74"
                    },
                    "device": {
                         "model" : "MOTO X",
                        "serialNumber" : "80528c008105b2df",
                        "manufactureDate" : "2010-08-15",
                        "inWarranty" : false
                    },        
                    "issues": [{
                        "code": 1,
                        "description": "Battery not charging"
                    },
                    {
                        "code": 2,
                        "description": "Broken display"
                    },
                    {
                        "code": 3,
                        "description": "Speaker out of order"
                    }],        
                    "appointmentStatus" : "pending",
                    "scheduling" : {
                        "location": {
                                "street": "R.Teodoro Sampaio, 758",
                                "city": "São Paulo",
                                "state": "São Paulo",
                                "zip": "05405-000",
                                "latitude": -23.557577,
                                "longitude": -46.677674,
                                "referencePoint" : "",
                                "distance": 1.2
                        },
                        "dateTime": "2015-04-01T08:41:51+00:00Z"
                    },
                    "complement" : "Minha bateria parou de carregar",
                    "distance" : ""
                },
                {
                    "appointmentCode" : "2",
                    "user" : {
                        "id" : 124,
                        "type" : 2,
                        "typeDescription" : "client",
                        "firstName": "william",
                        "lastName": "lowe",
                        "photo": "portraits/med/men/16.jpg",
                        "gender" : 1,
                        "email": "william.lowe46@example.com",
                        "phone" : "0763-530-575",
                        "mainUser" : false,
                        "about" : "Hi! I'm a moto client",
                        "username": "brownswan28"
                    },
                    "device": {
                        "model" : "MOTO MAXX",
                        "serialNumber" : "d7f6d409bc2c4968",
                        "manufactureDate" : "2012-04-27",
                        "inWarranty" : true
                    },        
                    "issues": [{
                        "code": 2,
                        "description": "Broken display"
                    }],        
                    "appointmentStatus" : "pending",
                    "scheduling" : {
                        "location": {
                                "street": "R. José Augusto Penteado, 45",
                                "city": "São Paulo",
                                "state": "São Paulo",
                                "zip": "01257-010",
                                "latitude": -23.5463084,
                                "longitude": -46.6903029,
                                "referencePoint" : "",
                                "distance": 1.2
                                
                        },
                        "dateTime": "2015-04-01T08:41:51+00:00Z"
                    },
                    "complement" : "Minha bateria parou de carregar",
                    "distance" : ""
                },
                {
                    "appointmentCode" : "3",
                    "user" : {
                        "id" : 123,
                        "type" : 2,
                        "typeDescription" : "client",
                        "firstName": "alex",
                        "lastName": "lewis",
                        "photo": "portraits/med/men/90.jpg",
                        "gender" : 1,
                        "email": "alex.lewis63@example.com",
                        "phone" : "(690)-934-4967",
                        "mainUser" : false,
                        "about" : "Hi! I'm a moto client",
                        "username": "tinyelephant874"
                    },
                    "device": {
                        "model" : "MOTO E",
                        "serialNumber" : "7df410b9bd8f9a17",
                        "manufactureDate" : "2014-03-05",
                        "inWarranty" : false
                    },        
                    "issues": [{
                        "code": 3,
                        "description": "Speaker out of order"
                    }],        
                    "appointmentStatus" : "accepted",
                    "scheduling" : {
                        "location": {
                               "street": "R. Natingui, 901",
                                "city": "São Paulo",
                                "state": "São Paulo",
                                "zip": "05443-001",
                                "latitude": -23.5546037,
                                "longitude": -46.696664,
                                "referencePoint" : "",
                                "distance": 1.2
                        },
                        "dateTime": "2015-04-01T08:41:51+00:00Z"
                    },
                    "complement" : "Minha bateria parou de carregar",
                    "distance" : ""
                },
                {
                    "appointmentCode" : "4",
                    "user" : {
                        "id" : 125,
                        "type" : 2,
                        "typeDescription" : "client",
                        "firstName": "Rafael",
                        "lastName": "Garg",
                        "photo": "portraits/med/men/68.jpg",
                        "gender" : 1,
                        "email" : "mototech@origamitech.com.br",
                        "phone" : "+55 11 98272-1828",
                        "mainUser" : false,
                        "about" : "Hi! I'm a moto client",
                        "username": "moto.origamitech"
                    },
                    "device": {
                         "model" : "MOTO X",
                        "serialNumber" : "80528c008105b2df",
                        "manufactureDate" : "2010-08-15",
                        "inWarranty" : true
                    },        
                    "issues": [{
                        "code": 1,
                        "description": "Battery not charging"
                    }],        
                    "appointmentStatus" : "pending",
                    "scheduling" : {
                        "location": {
                                "street": "R. Prof. Guilherme Milward, 396",
                                "city": "São Paulo",
                                "state": "São Paulo",
                                "zip": "00000-000",
                                "latitude": -23.5625369,
                                "longitude": -46.7104378,
                                "referencePoint" : "",
                                "distance": 1.2
                        },
                        "dateTime": "2015-04-01T08:41:51+00:00Z"
                    },
                    "complement" : "Minha bateria parou de carregar",
                    "distance" : ""
                },
                {
                    "appointmentCode" : "5",
                    "user" : {
                        "id" : 126,
                        "type" : 2,
                        "typeDescription" : "client",
                        "firstName": "brooke",
                        "lastName": "lord",
                        "photo": "portraits/med/women/23.jpg",
                        "gender" : 1,
                        "email": "brooke.lord30@example.com",
                        "phone" : "+55 11 98272-1828",
                        "mainUser" : false,
                        "about" : "Hi! I'm a moto client",
                        "username": "beautifulpeacock554"
                    },
                    "device": {
                        "model" : "MOTO G",
                        "serialNumber" : "721178cc25573580",
                        "manufactureDate" : "2014-07-03",
                        "inWarranty" : false
                    },        
                    "issues": [{
                        "code": 1,
                        "description": "Battery not charging"
                    }],        
                    "appointmentStatus" : "accepted",
                    "scheduling" : {
                        "location": {
                                "street": "R. Ferreira de Araújo, 653",
                                "city": "São Paulo",
                                "state": "São Paulo",
                                "zip": "05428-000",
                                "latitude": -23.563456,
                                "longitude": -46.697885,
                                "referencePoint" : "",
                                "distance": 1.2
                        },
                        "dateTime": "2015-04-01T08:41:51+00:00Z"
                    },
                    "complement" : "Minha bateria parou de carregar",
                    "distance" : ""
                },
                {
                    "appointmentCode" : "6",
                    "user" : {
                        "id" : 127,
                        "type" : 2,
                        "typeDescription" : "client",
                        "firstName": "maureen",
                        "lastName": "fowler",
                        "photo": "portraits/med/women/62.jpg",
                        "gender" : 1,
                        "email": "maureen.fowler98@example.com",
                        "phone": "(827)-257-9630",
                        "mainUser" : false,
                        "about" : "Hi! I'm a moto client",
                        "username": "purplekoala64"
                    },
                    "device": {
                        "model" : "MOTO G",
                        "serialNumber" : "721178cc25573580",
                        "manufactureDate" : "2014-07-03",
                        "inWarranty" : false
                    },        
                    "issues": [{
                        "code": 3,
                        "description": "Speaker out of order"
                    }],        
                    "appointmentStatus" : "accepted",
                    "scheduling" : {
                        "location": {
                                "street": "Av. Nove de Julho, 5224",
                                "city": "São Paulo",
                                "state": "São Paulo",
                                "zip": "01406-200",
                                "latitude": -23.5783311,
                                "longitude": -46.6755598,
                                "referencePoint" : "",
                                "distance": 1.2
                        },
                        "dateTime": "2015-04-01T08:41:51+00:00Z"
                    },
                    "complement" : "Minha bateria parou de carregar",
                    "distance" : ""
                },
                {
                    "appointmentCode" : "7",
                    "user" : {
                        "id" : 128,
                        "type" : 2,
                        "typeDescription" : "client",
                        "firstName": "gordon",
                        "lastName": "lord",
                        "photo": "portraits/med/men/17.jpg",
                        "gender" : 1,
                        "email": "gordon.lord87@example.com",
                        "phone": "(827)-257-9630",
                        "mainUser" : false,
                        "about" : "Hi! I'm a moto client",
                        "username": "orangefrog345"
                    },
                    "device": {
                        "model" : "MOTO X 2nd Gen",
                        "serialNumber" : "721178cc25573580",
                        "manufactureDate" : "2014-07-03",
                        "inWarranty" : false
                    },        
                    "issues": [{
                        "code": 1,
                        "description": "Battery not charging"
                    }],        
                    "appointmentStatus" : "accepted",
                    "scheduling" : {
                        "location": {
                                "street": "R. Maj. Sertório, 316",
                                "city": "São Paulo",
                                "state": "São Paulo",
                                "zip": "00000-000",
                                "latitude": -23.5466808,
                                "longitude": -46.6478013,
                                "referencePoint" : "",
                                "distance": 1.2
                        },
                        "dateTime": "2015-04-01T08:41:51+00:00Z"
                    },
                    "complement" : "Minha bateria parou de carregar",
                    "distance" : ""
                },
                {
                    "appointmentCode" : "8",
                    "user" : {
                        "id" : 129,
                        "type" : 2,
                        "typeDescription" : "client",
                        "firstName": "alice",
                        "lastName": "simmmons",
                        "photo": "portraits/med/women/33.jpg",
                        "gender" : 1,
                        "email": "alice.simmmons85@example.com",
                        "phone": "(827)-257-9630",
                        "mainUser" : false,
                        "about" : "Hi! I'm a moto client",
                        "username": "orangefrog345"
                    },
                    "device": {
                        "model" : "MOTO X 2nd Gen",
                        "serialNumber" : "721178cc25573580",
                        "manufactureDate" : "2014-07-03",
                        "inWarranty" : false
                    },        
                    "issues": [{
                        "code": 1,
                        "description": "Battery not charging"
                    }],        
                    "appointmentStatus" : "accepted",
                    "scheduling" : {
                        "location": {
                                "street": "R. Me. Teodora, 259",
                                "city": "São Paulo",
                                "state": "São Paulo",
                                "zip": "00000-000",
                                "latitude": -23.575230,
                                "longitude": -46.660673,
                                "referencePoint" : "",
                                "distance": 1.2
                        },
                        "dateTime": "2015-04-01T08:41:51+00:00Z"
                    },
                    "complement" : "Minha bateria parou de carregar",
                    "distance" : ""
                }]
        }

+ Response 400 (application/json)
        
        {
            "result" : {
                "success" : false,   
                "message" : "Error into request"
            },
            "data" : {
            }
        }

## User Dashboard [/v1/users/{id}/dashboard]
### Dashboard [GET]
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the User to perform action with. Has example value.

+ Response 200 (application/json)

        {
            "result" : {
                "success" : true,   
                "message" : ""
            },
            "data" : {
                "accepted": 9,
                "pending": 11,
                "open": 2
            }
        }

+ Response 400 (application/json)
        
        {
            "result" : {
                "success" : false,   
                "message" : "Error into dashboard request"
            },
            "data" : {
            }
        }

## User forgot password [/v1/users/forgotPwd]
### Forgot password [POST]
+ Request (application/json)

        { "email": "moto.origamitech@origamitech.com.br"}

+ Response 200 (application/json)

        {
            "result" : {
                "success" : true,   
                "message" : "Solicitacao de reset de senha recebido"
            },
            "data" : {
            }
        }

+ Response 400 (application/json)
        
        {
            "result" : {
                "success" : false,   
                "message" : "Erro no reset de senha"
            },
            "data" : {
            }
        }

## User received requests [/v1/users/{id}/appointments{?lat,lng,distance}]
### Received Requests [GET]
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the User to perform action with. Has example value.
    + lat (required, float, `-23.5630037`) ... Value of the user latitude . Has example value.
    + lng (required, float, ` -46.6864347`) ... Value of the user longitude . Has example value.
    + distance (required, number, `10`) ... The distance of the . Has example value.
+ Response 200 (application/json)

        {
            "result" : {
                "success" : true,
                "message" : ""
            },
            "data" : [{
                    "appointmentCode" : "1",
                    "user" : {
                        "id" : 121,
                        "type" : 2,
                        "typeDescription" : "client",
                        "firstName": "mark",
                        "lastName": "howard",
                        "photo": "portraits/med/men/55.jpg",
                        "gender" : 1,
                        "email": "mark.howard35@example.com",
                        "phone" : "0741-994-23",
                        "mainUser" : false,
                        "about" : "Hi! I'm a moto client",
                        "username": "whiteswan74"
                    },
                    "device": {
                         "model" : "MOTO X",
                        "serialNumber" : "80528c008105b2df",
                        "manufactureDate" : "2010-08-15",
                        "inWarranty" : false
                    },        
                    "issues": [{
                        "code": 1,
                        "description": "Battery not charging"
                    },
                    {
                        "code": 2,
                        "description": "Broken display"
                    },
                    {
                        "code": 3,
                        "description": "Speaker out of order"
                    }],        
                    "appointmentStatus" : "pending",
                    "scheduling" : {
                        "location": {
                                "street": "R. Cônego Eugênio Leite, 800",
                                "city": "São Paulo",
                                "state": "São Paulo",
                                "zip": "05414-001",
                                "latitude": -23.5620037,
                                "longitude":  -46.6814347,
                                "referencePoint" : "",
                                "distance": 1.2
                        },
                        "dateTime": "2015-04-01T08:41:51+00:00Z"
                    },
                    "complement" : "Minha bateria parou de carregar",
                    "distance" : ""
                },
                {
                    "appointmentCode" : "8",
                    "user" : {
                        "id" : 129,
                        "type" : 2,
                        "typeDescription" : "client",
                        "firstName": "alice",
                        "lastName": "simmmons",
                        "photo": "portraits/med/women/33.jpg",
                        "gender" : 1,
                        "email": "alice.simmmons85@example.com",
                        "phone": "(827)-257-9630",
                        "mainUser" : false,
                        "about" : "Hi! I'm a moto client",
                        "username": "orangefrog345"
                    },
                    "device": {
                        "model" : "MOTO X 2nd Gen",
                        "serialNumber" : "721178cc25573580",
                        "manufactureDate" : "2014-07-03",
                        "inWarranty" : false
                    },        
                    "issues": [{
                        "code": 1,
                        "description": "Battery not charging"
                    }],        
                    "appointmentStatus" : "accepted",
                    "scheduling" : {
                        "location": {
                                "street": "R. dos Macunis, 427",
                                "city": "São Paulo",
                                "state": "São Paulo",
                                "zip": "05444-001",
                                "latitude": -23.557138,
                                "longitude": -46.698162,
                                "referencePoint" : "",
                                "distance": 1.2
                        },
                        "dateTime": "2015-04-01T08:41:51+00:00Z"
                    },
                    "complement" : "Minha bateria parou de carregar",
                    "distance" : ""
                }
            ]
        }

+ Response 400 (application/json)
        
        {
            "result" : {
                "success" : false,   
                "message" : "Error into request"
            },
            "data" : {
            }
        }

## User Opened Services [/v1/users/{id}/openedServices]
### Opened Services [GET]
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the User to perform action with. Has example value.

+ Response 200 (application/json)

        {
            "result" : {
                "success" : true,
                "message" : ""
            },
            "data" : 
                [{
                    "number" : "WO00441331",
                    "swWarrantyStart" : "2014-04-01T08:41:51+00:00Z",
                    "swWarrantyEnd" : "2016-05-01T08:41:51+00:00Z",
                    "hwWarrantyStart" : "2014-04-01T08:41:51+00:00Z",
                    "hwWarrantyEnd" : "2016-07-01T08:41:51+00:00Z",        
                    "typeDescription" : "client",
                    "repairWarrantyStart": "2014-06-01T08:41:51+00:00Z",
                    "repairWarrantyEnd": "2014-07-01T08:41:51+00:00Z",
                    "entitlement": "XPTO",
                    "dueDate": "2015-04-25T08:41:51+00:00Z",
                    "statusDescription" : "Waiting parts",
                     "statusId" : 4,
                    "user" : {
                        "id" : 9871,
                        "type" : 2,
                        "typeDescription" : "client",
                        "firstName": "Vicent",
                        "lastName": "Matt",
                        "photo": "portraits/med/men/53.jpg",
                        "gender" : 1,
                        "email" : "mototech@origamitech.com.br",
                        "phone" : "+55 11 98272-1828",
                        "mainUser" : false,
                        "about" : "Hi! I'm a moto client",
                        "username": "moto.origamitech"
                    },
                    "device": {
                        "model" : "MOTO X",
                        "serialNumber" : "80528c008105b2df",
                        "manufactureDate" : "2010-08-15",
                        "inWarranty" : false
                    },        
                    "issues": [{
                        "code": 1,
                        "description": "Battery not charging"
                    },
                    {
                        "code": 2,
                        "description": "Broken display"
                    },
                    {
                        "code": 3,
                        "description": "Speaker out of order"
                    }]
                },
                {
                    "number" : "WO00441315",
                    "swWarrantyStart" : "2014-01-01T08:41:51+00:00Z",
                    "swWarrantyEnd" : "2014-02-01T08:41:51+00:00Z",
                    "hwWarrantyStart" : "2014-01-01T08:41:51+00:00Z",
                    "hwWarrantyEnd" : "2014-02-01T08:41:51+00:00Z",
                    "repairWarrantyStart": "2014-03-01T08:41:51+00:00Z",
                    "repairWarrantyEnd": "2014-04-01T08:41:51+00:00Z",
                    "dueDate": "2015-04-25T08:41:51+00:00Z",
                    "typeDescription" : "client",
                    "entitlement": "XPTO",
                    "statusDescription" : "Waiting repair",
                     "statusId" : 5,
                    "user" : {
                        "id" : 9872,
                        "type" : 2,
                        "typeDescription" : "client",
                        "firstName": "Rich",
                        "lastName": "Snyder",
                        "photo": "portraits/med/men/24.jpg",
                        "gender" : 1,
                        "email" : "mototech@origamitech.com.br",
                        "phone" : "+55 11 98272-1828",
                        "mainUser" : false,
                        "about" : "Hi! I'm a moto client",
                        "username": "moto.origamitech"
                    },
                    "device": {
                        "model" : "MOTO E 2nd Generation",
                        "serialNumber" : "721178cc25573580",
                        "manufactureDate" : "2010-08-15",
                        "inWarranty" : false
                    },        
                    "issues": [{
                        "code": 1,
                        "description": "Battery not charging"
                    },
                    {
                        "code": 2,
                        "description": "Broken display"
                    },
                    {
                        "code": 3,
                        "description": "Speaker out of order"
                    }]
                },
                {
                    "number" : "WO00442213",
                    "swWarrantyStart" : "2014-01-01T08:41:51+00:00Z",
                    "swWarrantyEnd" : "2014-02-01T08:41:51+00:00Z",
                    "hwWarrantyStart" : "2014-01-01T08:41:51+00:00Z",
                    "hwWarrantyEnd" : "2014-02-01T08:41:51+00:00Z",
                    "repairWarrantyStart": "2014-03-01T08:41:51+00:00Z",
                    "repairWarrantyEnd": "2014-04-01T08:41:51+00:00Z",
                    "dueDate": "2015-04-26T08:41:51+00:00Z",
                    "typeDescription" : "client",
                    "entitlement": "XPTO",
                    "statusDescription" : "Repaired",
                     "statusId" : 6,
                    "user" : {
                        "id" : 9873,
                        "type" : 2,
                        "typeDescription" : "client",
                        "firstName": "Roberto",
                        "lastName": "Fergoso",
                        "photo": "portraits/med/men/90.jpg",
                        "gender" : 1,
                        "email" : "mototech@origamitech.com.br",
                        "phone" : "+55 11 98272-1828",
                        "mainUser" : false,
                        "about" : "Hi! I'm a moto client",
                        "username": "moto.origamitech"
                    },
                    "device": {
                        "model" : "MOTO G",
                        "serialNumber" : "555667567",
                        "manufactureDate" : "2010-08-15",
                        "inWarranty" : false
                    },        
                    "issues": [{
                        "code": 1,
                        "description": "Battery not charging"
                    },
                    {
                        "code": 2,
                        "description": "Broken display"
                    },
                    {
                        "code": 3,
                        "description": "Speaker out of order"
                    }]
                },
                {
                    "number" : "WO004244113",
                    "swWarrantyStart" : "2014-01-01T08:41:51+00:00Z",
                    "swWarrantyEnd" : "2014-02-01T08:41:51+00:00Z",
                    "hwWarrantyStart" : "2014-01-01T08:41:51+00:00Z",
                    "hwWarrantyEnd" : "2014-02-01T08:41:51+00:00Z",
                    "repairWarrantyStart": "2014-03-01T08:41:51+00:00Z",
                    "repairWarrantyEnd": "2014-04-01T08:41:51+00:00Z",
                    "dueDate": "2014-12-01T08:41:51+00:00Z",      
                    "typeDescription" : "client",
                    "entitlement": "XPTO",
                    "statusDescription" : "Waiting Analysis",
                     "statusId" : 1,
                    "user" : {
                        "id" : 9874,
                        "type" : 2,
                        "typeDescription" : "client",
                        "firstName": "Dylan",
                        "lastName": "Long",
                        "photo": "portraits/med/men/85.jpg",
                        "gender" : 1,
                        "email" : "mototech@origamitech.com.br",
                        "phone" : "+55 11 98272-1828",
                        "mainUser" : false,
                        "about" : "Hi! I'm a moto client",
                        "username": "moto.origamitech"
                    },
                    "device": {
                        "model" : "MOTO MAXX",
                        "serialNumber" : "d7f6d409bc2c4968",
                        "manufactureDate" : "2010-08-15",
                        "inWarranty" : false
                    },        
                    "issues": [{
                        "code": 1,
                        "description": "Battery not charging"
                    },
                    {
                        "code": 2,
                        "description": "Broken display"
                    },
                    {
                        "code": 3,
                        "description": "Speaker out of order"
                    }]
                },
                {
                    "number" : "WO0204425413",
                    "swWarrantyStart" : "2014-01-01T08:41:51+00:00Z",
                    "swWarrantyEnd" : "2017-02-01T08:41:51+00:00Z",
                    "hwWarrantyStart" : "2014-01-01T08:41:51+00:00Z",
                    "hwWarrantyEnd" : "2017-02-01T08:41:51+00:00Z",
                    "repairWarrantyStart": "2014-03-01T08:41:51+00:00Z",
                    "repairWarrantyEnd": "2014-04-01T08:41:51+00:00Z",
                    "dueDate": "2014-12-01T08:41:51+00:00Z",
                    "typeDescription" : "client",
                    "entitlement": "XPTO",
                    "statusDescription" : "Waiting Analysis",
                     "statusId" : 1,
                    "user" : {
                        "id" : 9875,
                        "type" : 2,
                        "typeDescription" : "client",
                        "firstName": "Abbie",
                        "lastName": "Lane",
                        "photo": "portraits/med/women/84.jpg",
                        "gender" : 1,
                        "email" : "mototech@origamitech.com.br",
                        "phone" : "+55 11 98272-1828",
                        "mainUser" : false,
                        "about" : "Hi! I'm a moto client",
                        "username": "moto.origamitech"
                    },
                    "device": {
                        "model" : "MOTO G (2014)",
                        "serialNumber" : "abe03847ba34",
                        "manufactureDate" : "2010-08-15",
                        "inWarranty" : false
                    },        
                    "issues": [{
                        "code": 1,
                        "description": "Battery not charging"
                    },
                    {
                        "code": 2,
                        "description": "Broken display"
                    },
                    {
                        "code": 3,
                        "description": "Speaker out of order"
                    }]
                }]
        }

+ Response 400 (application/json)
        
        {
            "result" : {
                "success" : false,   
                "message" : "Error into request"
            },
            "data" : {
            }
        }

## User Past Services [/v1/users/{id}/pastServices]
### Past Services [GET]
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the User to perform action with. Has example value.

+ Response 200 (application/json)

        {
            "result" : {
                "success" : true,
                "message" : ""
            },
            "data" : 
                [{
                    "number" : "WO00441331",
                    "swWarrantyStart" : "2014-04-01T08:41:51+00:00Z",
                    "swWarrantyEnd" : "2014-05-01T08:41:51+00:00Z",
                    "hwWarrantyStart" : "2014-04-01T08:41:51+00:00Z",
                    "hwWarrantyEnd" : "2014-07-01T08:41:51+00:00Z",        
                    "typeDescription" : "client",
                    "repairWarrantyStart": "2014-06-01T08:41:51+00:00Z",
                    "repairWarrantyEnd": "2014-07-01T08:41:51+00:00Z",
                    "entitlement": "XPTO",
                    "dueDate": "2015-04-25T08:41:51+00:00Z",
                    "statusDescription" : "Waiting analysis",
                    "statusId" : 1,
                    "user" : {
                        "id" : 9871,
                        "type" : 2,
                        "typeDescription" : "client",
                        "firstName": "Vicent",
                        "lastName": "Matt",
                        "photo": "portraits/med/men/53.jpg",
                        "gender" : 1,
                        "email" : "mototech@origamitech.com.br",
                        "phone" : "+55 11 98272-1828",
                        "mainUser" : false,
                        "about" : "Hi! I'm a moto client",
                        "username": "moto.origamitech"
                    },
                    "device": {
                        "model" : "MOTO X",
                        "serialNumber" : "80528c008105b2df",
                        "manufactureDate" : "2010-08-15",
                        "inWarranty" : false
                    },        
                    "issues": [{
                        "code": 1,
                        "description": "Battery not charging"
                    },
                    {
                        "code": 2,
                        "description": "Broken display"
                    },
                    {
                        "code": 3,
                        "description": "Speaker out of order"
                    }]
                },
                {
                    "number" : "WO00441315",
                    "swWarrantyStart" : "2014-01-01T08:41:51+00:00Z",
                    "swWarrantyEnd" : "2014-02-01T08:41:51+00:00Z",
                    "hwWarrantyStart" : "2014-01-01T08:41:51+00:00Z",
                    "hwWarrantyEnd" : "2014-02-01T08:41:51+00:00Z",
                    "repairWarrantyStart": "2014-03-01T08:41:51+00:00Z",
                    "repairWarrantyEnd": "2014-04-01T08:41:51+00:00Z",
                    "dueDate": "2015-04-25T08:41:51+00:00Z",
                    "typeDescription" : "client",
                    "entitlement": "XPTO",
                    "statusDescription" : "Waiting approval",
                    "statusId" : 2,
                    "user" : {
                        "id" : 9872,
                        "type" : 2,
                        "typeDescription" : "client",
                        "firstName": "Rich",
                        "lastName": "Snyder",
                        "photo": "portraits/med/men/24.jpg",
                        "gender" : 1,
                        "email" : "mototech@origamitech.com.br",
                        "phone" : "+55 11 98272-1828",
                        "mainUser" : false,
                        "about" : "Hi! I'm a moto client",
                        "username": "moto.origamitech"
                    },
                    "device": {
                        "model" : "MOTO E 2nd Generation",
                        "serialNumber" : "721178cc25573580",
                        "manufactureDate" : "2010-08-15",
                        "inWarranty" : false
                    },        
                    "issues": [{
                        "code": 1,
                        "description": "Battery not charging"
                    },
                    {
                        "code": 2,
                        "description": "Broken display"
                    },
                    {
                        "code": 3,
                        "description": "Speaker out of order"
                    }]
                },
                {
                    "number" : "WO00442213",
                    "swWarrantyStart" : "2014-01-01T08:41:51+00:00Z",
                    "swWarrantyEnd" : "2014-02-01T08:41:51+00:00Z",
                    "hwWarrantyStart" : "2014-01-01T08:41:51+00:00Z",
                    "hwWarrantyEnd" : "2014-02-01T08:41:51+00:00Z",
                    "repairWarrantyStart": "2014-03-01T08:41:51+00:00Z",
                    "repairWarrantyEnd": "2014-04-01T08:41:51+00:00Z",
                    "dueDate": "2015-04-26T08:41:51+00:00Z",
                    "typeDescription" : "client",
                    "entitlement": "XPTO",
                    "statusDescription" : "Quote Rejected",
                    "statusId" : 3,
                    "user" : {
                        "id" : 9873,
                        "type" : 2,
                        "typeDescription" : "client",
                        "firstName": "Roberto",
                        "lastName": "Fergoso",
                        "photo": "portraits/med/men/90.jpg",
                        "gender" : 1,
                        "email" : "mototech@origamitech.com.br",
                        "phone" : "+55 11 98272-1828",
                        "mainUser" : false,
                        "about" : "Hi! I'm a moto client",
                        "username": "moto.origamitech"
                    },
                    "device": {
                        "model" : "MOTO G",
                        "serialNumber" : "555667567",
                        "manufactureDate" : "2010-08-15",
                        "inWarranty" : false
                    },        
                    "issues": [{
                        "code": 1,
                        "description": "Battery not charging"
                    },
                    {
                        "code": 2,
                        "description": "Broken display"
                    },
                    {
                        "code": 3,
                        "description": "Speaker out of order"
                    }]
                },
                {
                    "number" : "WO004244113",
                    "swWarrantyStart" : "2014-01-01T08:41:51+00:00Z",
                    "swWarrantyEnd" : "2014-02-01T08:41:51+00:00Z",
                    "hwWarrantyStart" : "2014-01-01T08:41:51+00:00Z",
                    "hwWarrantyEnd" : "2014-02-01T08:41:51+00:00Z",
                    "repairWarrantyStart": "2014-03-01T08:41:51+00:00Z",
                    "repairWarrantyEnd": "2014-04-01T08:41:51+00:00Z",
                    "dueDate": "2014-12-01T08:41:51+00:00Z",      
                    "typeDescription" : "client",
                    "entitlement": "XPTO",
                    "statusDescription" : "Waiting Parts",
                    "statusId" : 4,
                    "user" : {
                        "id" : 9874,
                        "type" : 2,
                        "typeDescription" : "client",
                        "firstName": "Dylan",
                        "lastName": "Long",
                        "photo": "portraits/med/men/85.jpg",
                        "gender" : 1,
                        "email" : "mototech@origamitech.com.br",
                        "phone" : "+55 11 98272-1828",
                        "mainUser" : false,
                        "about" : "Hi! I'm a moto client",
                        "username": "moto.origamitech"
                    },
                    "device": {
                        "model" : "MOTO MAXX",
                        "serialNumber" : "d7f6d409bc2c4968",
                        "manufactureDate" : "2010-08-15",
                        "inWarranty" : false
                    },        
                    "issues": [{
                        "code": 1,
                        "description": "Battery not charging"
                    },
                    {
                        "code": 2,
                        "description": "Broken display"
                    },
                    {
                        "code": 3,
                        "description": "Speaker out of order"
                    }]
                },
                {
                    "number" : "WO0204425413",
                    "swWarrantyStart" : "2014-01-01T08:41:51+00:00Z",
                    "swWarrantyEnd" : "2014-02-01T08:41:51+00:00Z",
                    "hwWarrantyStart" : "2014-01-01T08:41:51+00:00Z",
                    "hwWarrantyEnd" : "2014-02-01T08:41:51+00:00Z",
                    "repairWarrantyStart": "2014-03-01T08:41:51+00:00Z",
                    "repairWarrantyEnd": "2014-04-01T08:41:51+00:00Z",
                    "dueDate": "2014-12-01T08:41:51+00:00Z",
                    "typeDescription" : "client",
                    "entitlement": "XPTO",
                    "statusDescription" : "Waiting Repair",
                    "statusId" : 5,
                    "user" : {
                        "id" : 9875,
                        "type" : 2,
                        "typeDescription" : "client",
                        "firstName": "Abbie",
                        "lastName": "Lane",
                        "photo": "portraits/med/women/84.jpg",
                        "gender" : 1,
                        "email" : "mototech@origamitech.com.br",
                        "phone" : "+55 11 98272-1828",
                        "mainUser" : false,
                        "about" : "Hi! I'm a moto client",
                        "username": "moto.origamitech"
                    },
                    "device": {
                        "model" : "MOTO G (2014)",
                        "serialNumber" : "abe03847ba34",
                        "manufactureDate" : "2010-08-15",
                        "inWarranty" : false
                    },        
                    "issues": [{
                        "code": 1,
                        "description": "Battery not charging"
                    },
                    {
                        "code": 2,
                        "description": "Broken display"
                    },
                    {
                        "code": 3,
                        "description": "Speaker out of order"
                    }]
                }]
        }

+ Response 400 (application/json)
        
        {
            "result" : {
                "success" : false,   
                "message" : "Error into request"
            },
            "data" : {
            }
        }


## Issues [/v1/issues/list]
### Dashboard [GET]
+ Response 200 (application/json)
        
        {
            "result" : {
                "success" : true,   
                "message" : ""
            },
            "data" : [{
                "description":"Audio",
                "code":1,
                "issues":[{
                        "description":"Audio Issue 1",
                        "id": 1
                    },
                    {
                        "description":"Audio Issue 2",
                        "id": 2
                    }]
                },
                {
                "description":"Battery",
                "code":2,
                "issues":[{
                        "description":"Batery Issue 1",
                        "id": 3
                    },
                    {
                        "description":"Batery Issue 2",
                        "id": 4
                    }]
                },
                {
                "description":"Screen",
                    "code":3,
                    "issues":[{
                        "description":"Screen Issue 1",
                        "id": 5
                    },
                    {
                        "description":"Screen Issue 2",
                        "id": 6
                    }]
                },
                {
                "description":"Software",
                    "code":4,
                    "issues":[{
                        "description":"Software Issue 1",
                        "id": 7
                    },
                    {
                        "description":"Software Issue 2",
                        "id": 8
                    }]
                }]
        }
+ Response 400 (application/json)

         {
            "result" : {
                "success" : false,   
                "message" : "Error into request"
            },
            "data" : {
            }
        }

## Parts [/v1/parts/list]
### Dashboard [GET]
+ Response 200 (application/json)
        
        {
            "result" : {
                "success" : true,   
                "message" : ""
            },
            "data" : [{
                "description":"Audio",
                "code":1,
                "parts":[{
                        "description":"Audio Part 1 xpto",
                        "name":"Audio Part 1",
                        "picture":"http://randomimage.setgetgo.com/get.php?key=485035762&height=512&width=512&type=1",
                        "id": 1
                    },
                    {
                        "description":"Audio Part 2 xpto",
                        "name":"Audio Part 2",
                        "picture":"http://randomimage.setgetgo.com/get.php?key=35752937&height=512&width=512&type=1",
                        "id": 2
                    }]
                },
                {
                "description":"Battery",
                "code":2,
                "parts":[{
                        "description":"Battery Part 1 xpto",
                        "name":"Battery Part 1",
                        "picture":"http://randomimage.setgetgo.com/get.php?key=208222893&height=512&width=512&type=1",
                        "id": 3
                    },
                    {
                        "description":"Battery Part 2 xpto",
                        "name":"Battery Part 2",
                        "picture":"http://randomimage.setgetgo.com/get.php?key=752997661&height=512&width=512&type=1",
                        "id": 4
                    }]
                },
                {
                "description":"Screen",
                    "code":3,
                    "parts":[{
                        "description":"Screen Part 1 xpto",
                        "name":"Screen Part 1",
                        "picture":"http://randomimage.setgetgo.com/get.php?key=1263481711&height=512&width=512&type=1",
                        "id": 5
                    },
                    {
                        "description":"Screen Part 2",
                         "name":"Screen Part 2",
                        "picture":"http://randomimage.setgetgo.com/get.php?key=712079688&height=512&width=512&type=",
                        "id": 6
                    }]
                },
                {
                "description":"Wireless",
                    "code":4,
                    "parts":[{
                        "description":"Wireless Part 1 xpto",
                        "name":"Wireless Part 1",
                        "picture":"http://randomimage.setgetgo.com/get.php?key=937541993&height=512&width=512&type=",
                        "id": 7
                    },
                    {
                        "description":"Wireless Part 2 xpto",
                        "name":"Wireless Part 2",
                        "picture":"http://randomimage.setgetgo.com/get.php?key=937541993&height=512&width=512&type=",
                        "id": 8
                    }]
                }]
        }
+ Response 400 (application/json)

         {
            "result" : {
                "success" : false,   
                "message" : "Error into request"
            },
            "data" : {
            }
        }

## Notifications [/v1/users/{id}/notifications]
### User notifications [GET]
+ Response 200 (application/json)
        
        {
            "result" : {
                "success" : true,   
                "message" : ""
            },
            "data" : [{
                "id":1,
                "type":2,
                "description":"Audio",
                "subDescription":"subDescription",
                "objectGenericId":"objectGenericId",
                "user" : {
                        "id" : 9875,
                        "type" : 2,
                        "typeDescription" : "client",
                        "firstName": "Abbie",
                        "lastName": "Lane",
                        "photo": "portraits/med/women/84.jpg",
                        "gender" : 1,
                        "email" : "mototech@origamitech.com.br",
                        "phone" : "+55 11 98272-1828",
                        "mainUser" : false,
                        "about" : "Hi! I'm a moto client",
                        "username": "moto.origamitech"
                }
            },
            {
                "id":2,
                "type":1,
                "description":"Audio",
                "subDescription":"subDescription",
                "objectGenericId":"objectGenericId",
                "user" : {
                        "id" : 9871,
                        "type" : 2,
                        "typeDescription" : "client",
                        "firstName": "Vicent",
                        "lastName": "Matt",
                        "photo": "portraits/med/men/53.jpg",
                        "gender" : 1,
                        "email" : "mototech@origamitech.com.br",
                        "phone" : "+55 11 98272-1828",
                        "mainUser" : false,
                        "about" : "Hi! I'm a moto client",
                        "username": "moto.origamitech"
                }
            },
            {
                "id":3,
                "type":3,
                "description":"Audio",
                "subDescription":"subDescription",
                "objectGenericId":"objectGenericId",
                "user" : {
                        "id" : 9874,
                        "type" : 2,
                        "typeDescription" : "client",
                        "firstName": "Dylan",
                        "lastName": "Long",
                        "photo": "portraits/med/men/85.jpg",
                        "gender" : 1,
                        "email" : "mototech@origamitech.com.br",
                        "phone" : "+55 11 98272-1828",
                        "mainUser" : false,
                        "about" : "Hi! I'm a moto client",
                        "username": "moto.origamitech"
                }
            }]
        }
+ Response 400 (application/json)

         {
            "result" : {
                "success" : false,   
                "message" : "Error to request notification"
            },
            "data" : {
            }
        }

